--- STDOUT ---
INFO 06-25 22:03:07 [__init__.py:244] Automatically detected platform cuda.
When dataset path is not set, it will default to random dataset
Namespace(backend='vllm', dataset_name='random', dataset=None, dataset_path=None, input_len=1024, output_len=1024, n=1, num_prompts=200, hf_max_batch_size=None, output_json=None, async_engine=False, disable_frontend_multiprocessing=False, disable_detokenize=False, lora_path=None, prefix_len=None, random_range_ratio=None, hf_subset=None, hf_split=None, model='google/gemma-3-27b-it', task='auto', tokenizer='google/gemma-3-27b-it', tokenizer_mode='auto', trust_remote_code=False, dtype='auto', seed=0, hf_config_path=None, allowed_local_media_path='', revision=None, code_revision=None, rope_scaling={}, rope_theta=None, tokenizer_revision=None, max_model_len=2048, quantization='fp8', enforce_eager=False, max_seq_len_to_capture=8192, max_logprobs=20, disable_sliding_window=False, disable_cascade_attn=False, skip_tokenizer_init=False, enable_prompt_embeds=False, served_model_name=None, disable_async_output_proc=False, config_format='auto', hf_token=None, hf_overrides={}, override_neuron_config={}, override_pooler_config=None, logits_processor_pattern=None, generation_config='auto', override_generation_config={}, enable_sleep_mode=False, model_impl='auto', load_format='auto', download_dir=None, model_loader_extra_config={}, ignore_patterns=None, use_tqdm_on_load=True, qlora_adapter_name_or_path=None, pt_load_map_location='cpu', guided_decoding_backend='auto', guided_decoding_disable_fallback=False, guided_decoding_disable_any_whitespace=False, guided_decoding_disable_additional_properties=False, enable_reasoning=None, reasoning_parser='', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=2, data_parallel_size=1, data_parallel_size_local=None, data_parallel_address=None, data_parallel_rpc_port=None, data_parallel_backend='mp', enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, disable_custom_all_reduce=False, worker_cls='auto', worker_extension_cls='', enable_multimodal_encoder_data_parallel=False, block_size=None, gpu_memory_utilization=0.9, swap_space=4, kv_cache_dtype='auto', num_gpu_blocks_override=None, enable_prefix_caching=None, prefix_caching_hash_algo='builtin', cpu_offload_gb=0, calculate_kv_scales=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config={}, limit_mm_per_prompt={}, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=None, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=None, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', speculative_config=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, max_num_batched_tokens=None, max_num_seqs=None, max_num_partial_prefills=1, max_long_partial_prefills=1, cuda_graph_sizes=[512], long_prefill_token_threshold=0, num_lookahead_slots=0, scheduler_delay_factor=0.0, preemption_mode=None, num_scheduler_steps=1, multi_step_stream_outputs=True, scheduling_policy='fcfs', enable_chunked_prefill=None, disable_chunked_mm_input=False, scheduler_cls='vllm.core.scheduler.Scheduler', disable_hybrid_kv_cache_manager=False, kv_transfer_config=None, kv_events_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":null,"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":null,"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":null,"local_cache_dir":null}, additional_config={}, use_v2_block_manager=True, disable_log_stats=False, disable_log_requests=False)
INFO 06-25 22:03:17 [config.py:823] This model supports multiple tasks: {'generate', 'classify', 'reward', 'score', 'embed'}. Defaulting to 'generate'.
INFO 06-25 22:03:17 [config.py:1946] Defaulting to use mp for distributed inference
INFO 06-25 22:03:17 [config.py:2195] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 06-25 22:03:18 [core.py:455] Waiting for init message from front-end.
INFO 06-25 22:03:18 [core.py:70] Initializing a V1 LLM engine (v0.9.1) with config: model='google/gemma-3-27b-it', speculative_config=None, tokenizer='google/gemma-3-27b-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=fp8, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=google/gemma-3-27b-it, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
WARNING 06-25 22:03:18 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 112 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 06-25 22:03:18 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_2c0f633d'), local_subscribe_addr='ipc:///tmp/437c6eb5-466b-4af1-ad54-1f5080dc0e84', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 06-25 22:03:24 [utils.py:2737] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x78ceef76b7a0>
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:03:24 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_d0414b18'), local_subscribe_addr='ipc:///tmp/254cd5d0-e132-4a9c-82c8-66f739861e2e', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 06-25 22:03:24 [utils.py:2737] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x78d0620c1af0>
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:03:24 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_daedff5a'), local_subscribe_addr='ipc:///tmp/2ccb6f98-04e5-4333-b6b9-ae9d8538ba6d', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:03:25 [utils.py:1126] Found nccl from library libnccl.so.2
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:03:25 [pynccl.py:70] vLLM is using nccl==2.26.2
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:03:25 [utils.py:1126] Found nccl from library libnccl.so.2
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:03:25 [pynccl.py:70] vLLM is using nccl==2.26.2
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:03:56 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /mnt/disks/mlperf-scratch/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:03:56 [custom_all_reduce_utils.py:246] reading GPU P2P access cache from /mnt/disks/mlperf-scratch/gpu_p2p_access_cache_for_0,1,2,3,4,5,6,7.json
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:03:56 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_ab917396'), local_subscribe_addr='ipc:///tmp/c9a9c621-f2e9-4f52-9fd7-36c507d0ac53', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:03:56 [parallel_state.py:1065] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:03:56 [parallel_state.py:1065] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:01 [topk_topp_sampler.py:49] Using FlashInfer for top-p & top-k sampling.
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:01 [gpu_model_runner.py:1595] Starting to load model google/gemma-3-27b-it...
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:01 [topk_topp_sampler.py:49] Using FlashInfer for top-p & top-k sampling.
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:01 [gpu_model_runner.py:1595] Starting to load model google/gemma-3-27b-it...
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:01 [gpu_model_runner.py:1600] Loading model from scratch...
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:01 [cuda.py:240] Using FlashInfer backend on V1 engine by default for Blackwell (SM 10.0) GPUs.
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:01 [gpu_model_runner.py:1600] Loading model from scratch...
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:01 [cuda.py:240] Using FlashInfer backend on V1 engine by default for Blackwell (SM 10.0) GPUs.
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:01 [weight_utils.py:292] Using model weights format ['*.safetensors']
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:02 [weight_utils.py:292] Using model weights format ['*.safetensors']
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:09 [default_loader.py:272] Loading weights took 7.22 seconds
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:09 [gpu_model_runner.py:1624] Model loading took 13.9147 GiB and 7.719479 seconds
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:10 [default_loader.py:272] Loading weights took 8.05 seconds
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:10 [gpu_model_runner.py:1624] Model loading took 13.9147 GiB and 8.884987 seconds
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:10 [gpu_model_runner.py:1978] Encoder cache will be initialized with a budget of 16384 tokens, and profiled with 64 image items of the maximum feature size.
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:10 [gpu_model_runner.py:1978] Encoder cache will be initialized with a budget of 16384 tokens, and profiled with 64 image items of the maximum feature size.
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:26 [backends.py:462] Using cache directory: /mnt/disks/mlperf-scratch/torch_compile_cache/afec0cda80/rank_1_0 for vLLM's torch.compile
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:26 [backends.py:472] Dynamo bytecode transform time: 14.33 s
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:26 [backends.py:462] Using cache directory: /mnt/disks/mlperf-scratch/torch_compile_cache/afec0cda80/rank_0_0 for vLLM's torch.compile
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:26 [backends.py:472] Dynamo bytecode transform time: 14.48 s
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:37 [backends.py:135] Directly load the compiled graph(s) for shape None from the cache, took 9.445 s
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:37 [backends.py:135] Directly load the compiled graph(s) for shape None from the cache, took 9.500 s
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:43 [monitor.py:34] torch.compile takes 14.48 s in total
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:43 [monitor.py:34] torch.compile takes 14.33 s in total
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:04:44 [gpu_worker.py:227] Available KV cache memory: 139.79 GiB
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:04:44 [gpu_worker.py:227] Available KV cache memory: 139.79 GiB
WARNING 06-25 22:04:44 [kv_cache_utils.py:830] Add 8 padding layers, may waste at most 15.38% KV cache memory
INFO 06-25 22:04:44 [kv_cache_utils.py:870] GPU KV cache size: 523,504 tokens
INFO 06-25 22:04:44 [kv_cache_utils.py:874] Maximum concurrency for 2,048 tokens per request: 253.92x
WARNING 06-25 22:04:44 [kv_cache_utils.py:830] Add 8 padding layers, may waste at most 15.38% KV cache memory
INFO 06-25 22:04:44 [kv_cache_utils.py:870] GPU KV cache size: 523,504 tokens
INFO 06-25 22:04:44 [kv_cache_utils.py:874] Maximum concurrency for 2,048 tokens per request: 253.92x
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:05:00 [custom_all_reduce.py:196] Registering 8308 cuda graph addresses
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:05:00 [custom_all_reduce.py:196] Registering 8308 cuda graph addresses
[1;36m(VllmWorker rank=1 pid=72116)[0;0m INFO 06-25 22:05:00 [gpu_model_runner.py:2048] Graph capturing finished in 16 secs, took 1.21 GiB
[1;36m(VllmWorker rank=0 pid=72115)[0;0m INFO 06-25 22:05:00 [gpu_model_runner.py:2048] Graph capturing finished in 16 secs, took 1.21 GiB
INFO 06-25 22:05:00 [core.py:171] init engine (profile, create kv cache, warmup model) took 49.88 seconds
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527] WorkerProc hit an exception.
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527] Traceback (most recent call last):
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 522, in worker_busy_loop
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     output = func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     return func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 293, in execute_model
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     return func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1187, in execute_model
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self._prepare_inputs(scheduler_output))
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 689, in _prepare_inputs
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self.attn_metadata_builders[kv_cache_group_id].build(
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/attention/backends/flashinfer.py", line 484, in build
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self._plan(attn_metadata)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/attention/backends/flashinfer.py", line 317, in _plan
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self.global_hyperparameters = infer_global_hyperparameters(
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/attention/backends/flashinfer.py", line 125, in infer_global_hyperparameters
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     assert params == global_params, (
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]            ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527] AssertionError: FlashInfer backend currently only supports models in which all layers share the same values for the following hyperparameters: `window_left`, `logits_soft_cap`, `sm_scale`.
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527] Traceback (most recent call last):
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 522, in worker_busy_loop
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     output = func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     return func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 293, in execute_model
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     return func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1187, in execute_model
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self._prepare_inputs(scheduler_output))
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 689, in _prepare_inputs
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self.attn_metadata_builders[kv_cache_group_id].build(
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/attention/backends/flashinfer.py", line 484, in build
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self._plan(attn_metadata)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/attention/backends/flashinfer.py", line 317, in _plan
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     self.global_hyperparameters = infer_global_hyperparameters(
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/attention/backends/flashinfer.py", line 125, in infer_global_hyperparameters
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]     assert params == global_params, (
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527]            ^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527] AssertionError: FlashInfer backend currently only supports models in which all layers share the same values for the following hyperparameters: `window_left`, `logits_soft_cap`, `sm_scale`.
[1;36m(VllmWorker rank=0 pid=72115)[0;0m ERROR 06-25 22:05:07 [multiproc_executor.py:527] 
ERROR 06-25 22:05:07 [dump_input.py:69] Dumping input data
ERROR 06-25 22:05:07 [dump_input.py:71] V1 LLM engine (v0.9.1) with config: model='google/gemma-3-27b-it', speculative_config=None, tokenizer='google/gemma-3-27b-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=fp8, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=google/gemma-3-27b-it, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}, 
ERROR 06-25 22:05:07 [dump_input.py:79] Dumping scheduler output for model execution:
ERROR 06-25 22:05:07 [dump_input.py:80] SchedulerOutput(scheduled_new_reqs=[NewRequestData(req_id=0,prompt_token_ids_len=1024,mm_inputs=[],mm_hashes=[],mm_positions=[],sampling_params=SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=0, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=True, max_tokens=1024, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=None, extra_args=None),block_ids=([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64], [65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128], [129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192], [193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256], [257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320], [321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384], [385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448]),num_computed_tokens=0,lora_request=None)], scheduled_cached_reqs=[], num_scheduled_tokens={0: 1024}, total_num_scheduled_tokens=1024, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[64, 0, 0, 0, 0, 0, 0], finished_req_ids=[], free_encoder_input_ids=[], structured_output_request_ids={}, grammar_bitmask=null, kv_connector_metadata=null)
ERROR 06-25 22:05:07 [dump_input.py:82] SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, gpu_cache_usage=0.001960407625068772, prefix_cache_stats=PrefixCacheStats(reset=False, requests=1, queries=1024, hits=0), spec_decoding_stats=None)
ERROR 06-25 22:05:07 [core.py:517] EngineCore encountered a fatal error.
ERROR 06-25 22:05:07 [core.py:517] Traceback (most recent call last):
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 508, in run_engine_core
ERROR 06-25 22:05:07 [core.py:517]     engine_core.run_busy_loop()
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 535, in run_busy_loop
ERROR 06-25 22:05:07 [core.py:517]     self._process_engine_step()
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 560, in _process_engine_step
ERROR 06-25 22:05:07 [core.py:517]     outputs, model_executed = self.step_fn()
ERROR 06-25 22:05:07 [core.py:517]                               ^^^^^^^^^^^^^^
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 231, in step
ERROR 06-25 22:05:07 [core.py:517]     model_output = self.execute_model(scheduler_output)
ERROR 06-25 22:05:07 [core.py:517]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 217, in execute_model
ERROR 06-25 22:05:07 [core.py:517]     raise err
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 211, in execute_model
ERROR 06-25 22:05:07 [core.py:517]     return self.model_executor.execute_model(scheduler_output)
ERROR 06-25 22:05:07 [core.py:517]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 163, in execute_model
ERROR 06-25 22:05:07 [core.py:517]     (output, ) = self.collective_rpc("execute_model",
ERROR 06-25 22:05:07 [core.py:517]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 220, in collective_rpc
ERROR 06-25 22:05:07 [core.py:517]     result = get_response(w, dequeue_timeout)
ERROR 06-25 22:05:07 [core.py:517]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-25 22:05:07 [core.py:517]   File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 207, in get_response
ERROR 06-25 22:05:07 [core.py:517]     raise RuntimeError(
ERROR 06-25 22:05:07 [core.py:517] RuntimeError: Worker failed with error 'FlashInfer backend currently only supports models in which all layers share the same values for the following hyperparameters: `window_left`, `logits_soft_cap`, `sm_scale`.', please check the stack trace above for the root cause

--- STDERR ---
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
[1;36m(VllmWorker rank=1 pid=72116)[0;0m Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:   0% Completed | 0/12 [00:00<?, ?it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  17% Completed | 2/12 [00:00<00:03,  2.58it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  25% Completed | 3/12 [00:01<00:04,  1.93it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  33% Completed | 4/12 [00:02<00:04,  1.73it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  42% Completed | 5/12 [00:02<00:04,  1.64it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  50% Completed | 6/12 [00:03<00:03,  1.59it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  58% Completed | 7/12 [00:03<00:02,  1.72it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  67% Completed | 8/12 [00:04<00:02,  1.66it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  75% Completed | 9/12 [00:05<00:01,  1.62it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  83% Completed | 10/12 [00:05<00:01,  1.60it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards:  92% Completed | 11/12 [00:06<00:00,  1.59it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards: 100% Completed | 12/12 [00:07<00:00,  1.59it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m Loading safetensors checkpoint shards: 100% Completed | 12/12 [00:07<00:00,  1.67it/s]
[1;36m(VllmWorker rank=0 pid=72115)[0;0m 
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Adding requests:   0%|          | 0/200 [00:00<?, ?it/s]Adding requests:  12%|█▎        | 25/200 [00:00<00:00, 340.49it/s]
Traceback (most recent call last):
  File "/home/pirillo_google_com/vllm_benchmark/vllm-repo-benchmark/benchmarks/benchmark_throughput.py", line 724, in <module>
    main(args)
  File "/home/pirillo_google_com/vllm_benchmark/vllm-repo-benchmark/benchmarks/benchmark_throughput.py", line 407, in main
    elapsed_time, request_outputs = run_vllm(
                                    ^^^^^^^^^
  File "/home/pirillo_google_com/vllm_benchmark/vllm-repo-benchmark/benchmarks/benchmark_throughput.py", line 92, in run_vllm
    outputs = llm.generate(
              ^^^^^^^^^^^^^
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/utils.py", line 1267, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 464, in generate
    self._validate_and_add_requests(
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 1442, in _validate_and_add_requests
    self._add_request(
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 1462, in _add_request
    self.llm_engine.add_request(
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/llm_engine.py", line 207, in add_request
    self.engine_core.add_request(request)
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 653, in add_request
    self._send_input(EngineCoreRequestType.ADD, request)
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 629, in _send_input
    self.ensure_alive()
  File "/home/pirillo_google_com/.vllm/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 532, in ensure_alive
    raise EngineDeadError()
vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
